version: '2'
services:
  php:
    container_name: php
    build: .
    volumes:
      - ./:/docker/php
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
        - 3307:3306
    depends_on:
        - php
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

