version: '2'
services:
  php:
    container_name: php
    image: karinasergeevna/media-encoder:1.0
    volumes:
      - ./:/docker/php
      - ./output/:/docker/php/output
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/supervisor2/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - 9001:9001

