version: '2'
services:
  php:
    container_name: php
    build: .
    volumes:
      - ./:/docker/php
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/supervisor2/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - 9001:9001

