version: '2'
services:
  php:
    container_name: php
    build: .
    volumes:
      - ./:/docker/php
      - ./docker/supervisor/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:9001
    environment:
      QUEUE_CONNECTION: gearman
      QUEUE_DRIVER: gearman
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      EXTERNAL_API_URL: http://encode.dev.asdat.org
      BEANS_HOST: beanstalkd
      GEARMAN_HOST: gearman

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.5-management
    hostname: app-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /home/encode/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /

  beanstalkd:
    container_name: beanstalkd
    image: schickling/beanstalkd:latest
    restart: always
    ports:
      - "11300:11300"

  gearman:
    image: kendu/gearman