version: '2'
services:
  php:
    container_name: php
    build: .
    volumes:
      - ./:/docker/php
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - ffmpeg
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 3307:3306
    depends_on:
        - php
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  ffmpeg:
    container_name: ffmpeg
    image: jrottenberg/ffmpeg:3.4-scratch
    volumes:
      - /tmp/manager:/docker/php

