version: '2'
services:
  php:
    container_name: php
    image: media-encoder:latest
    volumes:
      - ./output/:/docker/php/output
      - ./docker/supervisor/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:9001
    environment:
      QUEUE_CONNECTION: rabbitmq
      QUEUE_DRIVER: rabbitmq
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      EXTERNAL_API_URL: http://encode.dev.asdat.org

