version: '2'
services:
  php:
    container_name: php
    build: .
    volumes:
      - ./:/docker/php
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
        - 3307:3306
    depends_on:
        - php
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
