version: '2'
services:
  php:
    container_name: php
    image: karinasergeevna/media-encoder:1.0.3
    volumes:
      - ./output/:/docker/php/output
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/supervisor2/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./.env:/docker/php/.env
    ports:
      - 9001:9001
    environment:
      QUEUE_CONNECTION: rabbitmq
      QUEUE_DRIVER: rabbitmq
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      EXTERNAL_API_URL: http://encode.dev.asdat.org
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.5-management
    hostname: app-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /home/encode:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /

