version: '2'
services:
  php-pubsub-kafka:
    container_name: php_container
    build: .
    depends_on:
      - "kafka"
    volumes:
      - ./:/opt/php-pubsub
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_BROKER: 94.130.75.108
  zookeeper:
    container_name: zookeeper_container
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    container_name: kafka_container
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${HOSTIP}:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOSTIP}:9092
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: ${HOSTIP}:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: ${HOSTIP}:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_PUBLISH_MS: 1000
      KAFKA_JMX_PORT: 7999
      KAFKA_JMX_HOSTNAME: ${HOSTIP}
