version: '2'
services:
  php:
    container_name: php
    image: karinasergeevna/media-encoder:1.0.2
    volumes:
      - ./output/:/docker/php/output
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:9001

